version: "2"

services:

  node:
    image: node:18-alpine
    user: "node"
    working_dir: /home/node/app
    container_name: vue_app
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - "8080:8080"
    command: "npm run serve"
